# TP4/configs/sage_sampling.yaml
seed: 42
device: "cuda"
epochs: 50
lr: 0.01
weight_decay: 5e-4

sage:
  hidden_dim: 64
  dropout: 0.5

sampling:
  batch_size: 256
  num_neighbors_l1: 10
  num_neighbors_l2: 10